/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dr.challan;

import com.dr.connection.DatabaseConnection;
import com.dr.login.MainScreen;
import com.dr.utils.PrintUtilities;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dinesh
 */
public class PrintChallan extends javax.swing.JFrame {

    /**
     * Creates new form PrintChallan
     */
    public PrintChallan() {
        initComponents();
        populateChallanNumberComboBox();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        separatorBelowName = new javax.swing.JSeparator();
        namePanel = new javax.swing.JPanel();
        ChallanOwnerName = new javax.swing.JLabel();
        Adress1 = new javax.swing.JLabel();
        separatorBelowItemTable = new javax.swing.JSeparator();
        separatorBelowChallanLabel = new javax.swing.JSeparator();
        challanAndDatePanel = new javax.swing.JPanel();
        mrLabel = new javax.swing.JLabel();
        separatorSideByCustomerName = new javax.swing.JSeparator();
        separatorSideChallanName = new javax.swing.JSeparator();
        challanLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        customerNameTextField = new javax.swing.JLabel();
        challanNoTextField = new javax.swing.JLabel();
        dateTextField = new javax.swing.JLabel();
        separatorBelowChallanAndDate = new javax.swing.JSeparator();
        itemTablePanel = new javax.swing.JPanel();
        itemTableScrollPane = new javax.swing.JScrollPane();
        itemTable = new javax.swing.JTable();
        recievedByPanel = new javax.swing.JPanel();
        receivedByLabel = new javax.swing.JLabel();
        receivedByLine = new javax.swing.JSeparator();
        preparedByLabel = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        preparedByLine = new javax.swing.JSeparator();
        totalAmountTextField = new javax.swing.JLabel();
        salesChallanLabelPanel = new javax.swing.JPanel();
        SalesChallenLabel = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        Mobile1 = new javax.swing.JLabel();
        Mobile2 = new javax.swing.JLabel();
        challanNumberComboBox = new javax.swing.JComboBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mainPanel.setPreferredSize(new java.awt.Dimension(578, 360));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        separatorBelowName.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 580, -1));

        namePanel.setBackground(new java.awt.Color(255, 255, 255));

        ChallanOwnerName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ChallanOwnerName.setText("     DINESH  RIBBONS     ");
        namePanel.add(ChallanOwnerName);

        Adress1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Adress1.setText("1/14 Khatodra Industrial Soc., Behind Sub-Jail, Ring Road, SURAT");
        namePanel.add(Adress1);

        mainPanel.add(namePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 320, 40));

        separatorBelowItemTable.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowItemTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 600, -1));

        separatorBelowChallanLabel.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowChallanLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, 580, -1));

        challanAndDatePanel.setBackground(new java.awt.Color(255, 255, 255));

        mrLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        mrLabel.setText("M/S :");

        separatorSideByCustomerName.setForeground(new java.awt.Color(0, 0, 0));
        separatorSideByCustomerName.setOrientation(javax.swing.SwingConstants.VERTICAL);

        separatorSideChallanName.setForeground(new java.awt.Color(0, 0, 0));
        separatorSideChallanName.setOrientation(javax.swing.SwingConstants.VERTICAL);

        challanLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        challanLabel.setText("Challan No :");

        dateLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        dateLabel.setText("Date :");

        customerNameTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        customerNameTextField.setText("-");

        challanNoTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        challanNoTextField.setText("-");

        dateTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dateTextField.setText("-");

        javax.swing.GroupLayout challanAndDatePanelLayout = new javax.swing.GroupLayout(challanAndDatePanel);
        challanAndDatePanel.setLayout(challanAndDatePanelLayout);
        challanAndDatePanelLayout.setHorizontalGroup(
            challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(challanAndDatePanelLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(mrLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorSideByCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(challanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(challanNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorSideChallanName, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addContainerGap())
        );
        challanAndDatePanelLayout.setVerticalGroup(
            challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(challanAndDatePanelLayout.createSequentialGroup()
                .addGroup(challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorSideByCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separatorSideChallanName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(challanAndDatePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mrLabel)
                                .addComponent(customerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(challanLabel)
                                .addComponent(challanNoTextField))
                            .addGroup(challanAndDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dateLabel)
                                .addComponent(dateTextField)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(challanAndDatePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 560, 40));

        separatorBelowChallanAndDate.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowChallanAndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 580, -1));

        itemTablePanel.setBackground(new java.awt.Color(255, 255, 255));
        itemTablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        itemTableScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        itemTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        itemTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        itemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        itemTableScrollPane.setViewportView(itemTable);

        itemTablePanel.add(itemTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 190));

        mainPanel.add(itemTablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 560, 200));

        recievedByPanel.setBackground(new java.awt.Color(255, 255, 255));

        receivedByLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        receivedByLabel.setText("Received By :");

        receivedByLine.setForeground(new java.awt.Color(51, 51, 51));

        preparedByLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        preparedByLabel.setText("Prepared By: ");

        totalAmountLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        totalAmountLabel.setText("Total Amount :");

        preparedByLine.setForeground(new java.awt.Color(51, 51, 51));

        totalAmountTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        totalAmountTextField.setText("-");

        javax.swing.GroupLayout recievedByPanelLayout = new javax.swing.GroupLayout(recievedByPanel);
        recievedByPanel.setLayout(recievedByPanelLayout);
        recievedByPanelLayout.setHorizontalGroup(
            recievedByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recievedByPanelLayout.createSequentialGroup()
                .addComponent(receivedByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receivedByLine, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preparedByLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preparedByLine, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(totalAmountLabel)
                .addGap(5, 5, 5)
                .addComponent(totalAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        recievedByPanelLayout.setVerticalGroup(
            recievedByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recievedByPanelLayout.createSequentialGroup()
                .addGroup(recievedByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(recievedByPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(preparedByLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(recievedByPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(recievedByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(receivedByLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(recievedByPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(receivedByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(preparedByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(totalAmountTextField)))))
                .addGap(0, 0, 0))
        );

        mainPanel.add(recievedByPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 560, -1));

        salesChallanLabelPanel.setBackground(new java.awt.Color(255, 255, 255));
        salesChallanLabelPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SalesChallenLabel.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        SalesChallenLabel.setText("SALES CHALLAN");
        salesChallanLabelPanel.add(SalesChallenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 100, 20));

        mainPanel.add(salesChallanLabelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 560, 20));

        menuButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        mainPanel.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        printButton.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        printButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printButtonKeyPressed(evt);
            }
        });
        mainPanel.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 60, -1));

        Mobile1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Mobile1.setText("Anjesh : 09227456635 ");
        mainPanel.add(Mobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Mobile2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Mobile2.setText(" Dinesh : 9228414858");
        mainPanel.add(Mobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, -1));

        challanNumberComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        challanNumberComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challanNumberComboBoxActionPerformed(evt);
            }
        });
        mainPanel.add(challanNumberComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        printButton.setVisible(false);
        challanNumberComboBox.setVisible(false);
        menuButton.setVisible(false);
        PrintUtilities.printComponent(this);
        printButton.setVisible(true);
        menuButton.setVisible(true);
    }//GEN-LAST:event_printButtonActionPerformed

    private void printButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printButtonKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode())
        {
            case KeyEvent.VK_ENTER:
            printButtonActionPerformed(null);
        }
    }//GEN-LAST:event_printButtonKeyPressed

    private void challanNumberComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challanNumberComboBoxActionPerformed
       DatabaseConnection conn = new DatabaseConnection();
        String customerName = "";
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = dateFormat.format(new Date());
        ResultSet salesDetailsResultSet = conn.getSalesDetailsByInvoiceNo(challanNumberComboBox.getSelectedItem().toString());
        if(salesDetailsResultSet != null) {
            try {
                while(salesDetailsResultSet.next()) {
                    customerName = salesDetailsResultSet.getString("bill_to");
                }
            } catch (SQLException ex) {
                Logger.getLogger(PrintChallan.class.getName()).log(Level.SEVERE, null, ex);
            }finally {
                //close all database connections
                conn.dbClose();
            }
        }
        customerNameTextField.setText(customerName);
        dateTextField.setText(date);
        challanNoTextField.setText(challanNumberComboBox.getSelectedItem().toString());
        ResultSet salesItemsResultSet = conn.getItemIableByInvoiceNo(challanNumberComboBox.getSelectedItem().toString());
        itemTable.setModel(DbUtils.resultSetToTableModel(salesItemsResultSet));
        itemTable.getColumnModel().getColumn(0).setMinWidth(50);
        itemTable.getColumnModel().getColumn(0).setMaxWidth(50);
        itemTable.getColumnModel().getColumn(1).setMinWidth(150);
        itemTable.getColumnModel().getColumn(2).setMinWidth(60);
        itemTable.getColumnModel().getColumn(2).setMaxWidth(60);
        itemTable.getColumnModel().getColumn(3).setMinWidth(90);
        itemTable.getColumnModel().getColumn(4).setMinWidth(80);
        itemTable.getColumnModel().getColumn(4).setMinWidth(90);
        
        itemTable.setFont(new java.awt.Font("Times New Roman", 0, 12));
        itemTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        
        BigDecimal total_amount = new BigDecimal(0);
        for (int i = 0; i < itemTable.getRowCount(); i++) {

            if (itemTable.getValueAt(i, 0) == null || itemTable.getValueAt(i, 0).equals("")) {
                break;
            } else {
                BigDecimal amount = BigDecimal.valueOf(Double.parseDouble(itemTable.getValueAt(i, 5).toString()));
                total_amount = total_amount.add(amount);
            }
        }
        totalAmountTextField.setText(String.valueOf(total_amount));
    }//GEN-LAST:event_challanNumberComboBoxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menuButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        MainScreen ss = new MainScreen();
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void populateChallanNumberComboBox() {
        DatabaseConnection conn = new DatabaseConnection();
        Iterator<String> iterator = conn.getInvoiceNo().iterator();
        while (iterator.hasNext()) {
                challanNumberComboBox.addItem(iterator.next());
        }
        int lastInvoiceNumber = conn.getLast_Inv_No();
        challanNumberComboBox.setSelectedItem(lastInvoiceNumber);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintChallan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintChallan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintChallan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintChallan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintChallan().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress1;
    private javax.swing.JLabel ChallanOwnerName;
    private javax.swing.JLabel Mobile1;
    private javax.swing.JLabel Mobile2;
    private javax.swing.JLabel SalesChallenLabel;
    private javax.swing.JPanel challanAndDatePanel;
    private javax.swing.JLabel challanLabel;
    private javax.swing.JLabel challanNoTextField;
    private javax.swing.JComboBox challanNumberComboBox;
    private javax.swing.JLabel customerNameTextField;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateTextField;
    private javax.swing.JTable itemTable;
    private javax.swing.JPanel itemTablePanel;
    private javax.swing.JScrollPane itemTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JLabel mrLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JLabel preparedByLabel;
    private javax.swing.JSeparator preparedByLine;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel receivedByLabel;
    private javax.swing.JSeparator receivedByLine;
    private javax.swing.JPanel recievedByPanel;
    private javax.swing.JPanel salesChallanLabelPanel;
    private javax.swing.JSeparator separatorBelowChallanAndDate;
    private javax.swing.JSeparator separatorBelowChallanLabel;
    private javax.swing.JSeparator separatorBelowItemTable;
    private javax.swing.JSeparator separatorBelowName;
    private javax.swing.JSeparator separatorSideByCustomerName;
    private javax.swing.JSeparator separatorSideChallanName;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel totalAmountTextField;
    // End of variables declaration//GEN-END:variables
}
