/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dr.print;

import com.dr.connection.DatabaseConnection;
import com.dr.login.MainScreen;
import com.dr.utils.Calendarium;
import com.dr.utils.PrintUtilities;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Dinesh
 */
public class PrintPartywiseSalesDetails extends javax.swing.JFrame {
     DatabaseConnection db = new DatabaseConnection();
     DateFormat dateFormat_dd_MM_yyyy = new SimpleDateFormat("dd-MM-yyyy");

    /**
     * Creates new form PrintPartywiseSalesDetails
     */
    public PrintPartywiseSalesDetails(String partyName, String fromDate, String toDate) {
        initComponents();
        setLocationRelativeTo(null);
        
        partyNameField.setText(partyName);
        fromDateField.setText(fromDate);
        toDateField.setText(toDate);
        populateCustomerNameComboBox();
        if(!partyName.equals("") && !fromDate.equals("") && !toDate.equals("")) {
            partyNameComboBox.setSelectedItem(partyName);
            goButtonActionPerformed(null);
        }
        
    }
    
    private void populateCustomerNameComboBox() {
        DatabaseConnection conn = new DatabaseConnection();
        Iterator<String> iterator = conn.getCustomerNameFromSaleDetails().iterator();
        while (iterator.hasNext()) {
            partyNameComboBox.addItem(iterator.next());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        namePanel = new javax.swing.JPanel();
        ChallanOwnerName = new javax.swing.JLabel();
        Adress1 = new javax.swing.JLabel();
        separatorBelowName = new javax.swing.JSeparator();
        Mobile1 = new javax.swing.JLabel();
        Mobile2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        partyNameComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        partyNameField = new javax.swing.JLabel();
        fromDateField = new javax.swing.JLabel();
        toDateField = new javax.swing.JLabel();
        fromDateButton = new javax.swing.JButton();
        toDateButton = new javax.swing.JButton();
        goButton = new javax.swing.JButton();
        separatorBelowName2 = new javax.swing.JSeparator();
        separatorBelowName3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertyTable = new javax.swing.JTable();
        menuButton = new javax.swing.JButton();
        totalAmountField = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        separatorBelowName1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namePanel.setBackground(new java.awt.Color(255, 255, 255));
        namePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ChallanOwnerName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ChallanOwnerName.setText("     DINESH  RIBBONS     ");
        namePanel.add(ChallanOwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 5, -1, -1));

        Adress1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        Adress1.setText("1/14 Khatodra Industrial Soc., Behind Sub-Jail, Ring Road, SURAT");
        namePanel.add(Adress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 27, -1, -1));

        mainPanel.add(namePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 320, 40));

        separatorBelowName.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 700, 10));

        Mobile1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Mobile1.setText("Anjesh : 09227456635 ");
        mainPanel.add(Mobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Mobile2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Mobile2.setText(" Dinesh : 9228414858");
        mainPanel.add(Mobile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("M/s :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("From :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 40, -1, -1));

        partyNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL" }));
        partyNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyNameComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(partyNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("To :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        partyNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        partyNameField.setText("-");
        jPanel1.add(partyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 2, 310, -1));

        fromDateField.setBackground(new java.awt.Color(255, 255, 255));
        fromDateField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fromDateField.setText("-");
        jPanel1.add(fromDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 130, -1));

        toDateField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        toDateField.setText("-");
        jPanel1.add(toDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 120, -1));

        fromDateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/calendar_icon1(2).png"))); // NOI18N
        fromDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromDateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(fromDateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 30, 20));

        toDateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/calendar_icon1(2).png"))); // NOI18N
        toDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toDateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(toDateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 30, 20));

        goButton.setText("Go");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });
        jPanel1.add(goButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 48, -1));

        mainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 75, 690, 70));

        separatorBelowName2.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 580, -1));

        separatorBelowName3.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 58, 580, -1));

        jLabel4.setText("Prepared by :");
        mainPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 85, -1));

        jLabel5.setText("Customer Sign :");
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 770, -1, -1));

        totalAmountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalAmountLabel.setText("Total Amount :  ");
        mainPanel.add(totalAmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 690, -1, -1));

        propertyTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        propertyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(propertyTable);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 165, 670, 500));

        menuButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        menuButton.setText("Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        mainPanel.add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        totalAmountField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalAmountField.setText("-");
        mainPanel.add(totalAmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 140, -1));

        printButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        printButton.setText("Print");
        printButton.setPreferredSize(new java.awt.Dimension(63, 23));
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        printButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                printButtonKeyPressed(evt);
            }
        });
        mainPanel.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 60, -1));

        separatorBelowName1.setForeground(new java.awt.Color(0, 0, 0));
        mainPanel.add(separatorBelowName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 700, 10));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/DINESH LOGO small_white_bg.jpg"))); // NOI18N
        mainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/DINESH LOGO small_white_bg.jpg"))); // NOI18N
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromDateButtonActionPerformed
        // TODO add your handling code here:
        Calendarium cal = new Calendarium(new JFrame());
        cal.displayDate();
        fromDateField.setText(cal.setPickedDate());
    }//GEN-LAST:event_fromDateButtonActionPerformed

    private void toDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toDateButtonActionPerformed
        // TODO add your handling code here:
        Calendarium cal = new Calendarium(new JFrame());
        cal.displayDate();
        toDateField.setText(cal.setPickedDate());
    }//GEN-LAST:event_toDateButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        printButton.setVisible(false);
        menuButton.setVisible(false);
        partyNameComboBox.setVisible(false);
        fromDateButton.setVisible(false);
        toDateButton.setVisible(false);
        goButton.setVisible(false);
        PrintUtilities.printComponent(this);
        printButton.setVisible(true);
        menuButton.setVisible(true);
        partyNameComboBox.setVisible(true);
        fromDateButton.setVisible(true);
        toDateButton.setVisible(true);
        goButton.setVisible(false);
    }//GEN-LAST:event_printButtonActionPerformed

    private void printButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_printButtonKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode())
        {
            case KeyEvent.VK_ENTER:
            printButtonActionPerformed(null);
        }
    }//GEN-LAST:event_printButtonKeyPressed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        MainScreen ss = new MainScreen();
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
         boolean Flag = false;
        String f_date = null;
        String t_date = null;

        if (Flag == false) {
            if (fromDateField.getText().equals("") || fromDateField.getText() == null) {
                String message1 = "From date: Should not be left empty!!";
                JOptionPane.showMessageDialog(new JFrame(), message1,
                        "Error", JOptionPane.ERROR_MESSAGE);
                Flag = true;
            }


        }

        if (Flag == false) {
            if (toDateField.getText().equals("") || toDateField.getText() == null) {
                String message1 = "To Date: Should not be left empty!!";
                JOptionPane.showMessageDialog(new JFrame(), message1,
                        "Error", JOptionPane.ERROR_MESSAGE);
                Flag = true;
            }


        }

        if (Flag == false) {
            String dt = fromDateField.getText().toString();

            try {
                Date d1 = dateFormat_dd_MM_yyyy.parse(dt);
                System.out.println(d1);

                DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
                f_date = df1.format(d1);
                System.out.println(f_date);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Invalid Date.\nDate Format should be (dd-MM-yyyy)");
                Flag = true;
                //Logger.getLogger(Amount_paid.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

        if (Flag == false) {
            String dt = toDateField.getText().toString();

            try {
                Date d1 = dateFormat_dd_MM_yyyy.parse(dt);
                System.out.println(d1);

                DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
                t_date = df1.format(d1);
                System.out.println(t_date);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Invalid Date.\nDate Format should be (dd-MM-yyyy)");
                Flag = true;
                //Logger.getLogger(Amount_paid.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

        if (Flag == false) {

            try {
                db.dbConn();
                String CustomerName = (String) partyNameComboBox.getSelectedItem();
                String sql = "SELECT bill_to AS 'Party Name', dc_no AS 'Invoice No.', DATE_FORMAT(dc_date, '%d/%m/%Y' ) AS 'Date', total_amt AS 'Total Amount' FROM sales_details WHERE dc_date BETWEEN '" + f_date + "' AND '" + t_date + "' ORDER BY dc_date ASC";
                if (!CustomerName.equals("ALL")) {
                    sql = "SELECT bill_to AS 'Party Name', dc_no AS 'Invoice No.', DATE_FORMAT(dc_date, '%d/%m/%Y' ) AS 'Date', total_amt AS 'Total Amount' " +  
                            "FROM sales_details WHERE dc_date BETWEEN '" + f_date + "' AND '" + t_date + "' " + " AND bill_to = '" + CustomerName + "' ORDER BY dc_date ASC";
                    
                }
                System.out.println(sql);
                ResultSet rs = db.statement.executeQuery(sql);


                propertyTable.setModel(DbUtils.resultSetToTableModel(rs));
                propertyTable.setFont(new java.awt.Font("Times New Roman", 0, 14));





                setAmountCostGrossValue();
                db.dbClose();
            } catch (SQLException sqle) {
                sqle.printStackTrace();
            }
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void partyNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partyNameComboBoxActionPerformed
        partyNameField.setText(partyNameComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_partyNameComboBoxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menuButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing
                               
    private void setAmountCostGrossValue() {
        BigDecimal total_amt = new BigDecimal(0);
        for (int i = 0; i < propertyTable.getRowCount(); i++) {

            if (propertyTable.getValueAt(i, 0) != null || !propertyTable.getValueAt(i, 0).equals("")) {
                BigDecimal amt = BigDecimal.valueOf(Double.parseDouble(propertyTable.getValueAt(i, 3).toString()));
                total_amt = total_amt.add(amt);
            }
        }
        totalAmountField.setText(String.valueOf(total_amt));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintPartywiseSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintPartywiseSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintPartywiseSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintPartywiseSalesDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintPartywiseSalesDetails("", "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress1;
    private javax.swing.JLabel ChallanOwnerName;
    private javax.swing.JLabel Mobile1;
    private javax.swing.JLabel Mobile2;
    private javax.swing.JButton fromDateButton;
    private javax.swing.JLabel fromDateField;
    private javax.swing.JButton goButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel namePanel;
    private javax.swing.JComboBox partyNameComboBox;
    private javax.swing.JLabel partyNameField;
    private javax.swing.JButton printButton;
    private javax.swing.JTable propertyTable;
    private javax.swing.JSeparator separatorBelowName;
    private javax.swing.JSeparator separatorBelowName1;
    private javax.swing.JSeparator separatorBelowName2;
    private javax.swing.JSeparator separatorBelowName3;
    private javax.swing.JButton toDateButton;
    private javax.swing.JLabel toDateField;
    private javax.swing.JLabel totalAmountField;
    private javax.swing.JLabel totalAmountLabel;
    // End of variables declaration//GEN-END:variables
}
