/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dr.sales;

import com.dr.connection.DatabaseConnection;
import com.dr.login.MainScreen;
import com.dr.print.PrintPartywiseSalesDetails;
import com.dr.utils.Calendarium;
import com.dr.utils.Validation;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author RAM
 */
public class Show_sales extends javax.swing.JFrame implements ActionListener {

    DatabaseConnection db = new DatabaseConnection();
    Validation valid = new Validation();
    private static final int DELAY_TIME = 165;

    /**
     * Creates new form Show_sales
     */
    public Show_sales() {
        initComponents();
        Timer timer = new Timer(DELAY_TIME, this);
        timer.start();
        setLocationRelativeTo(null);
        populateCustomerNameComboBox();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String oldText = scrollLabel.getText();
        String newText = oldText.substring(1) + oldText.substring(0, 1);
        scrollLabel.setText(newText);
    }

    public void cleartable() {
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            for (int k = 0; k < jTable1.getColumnCount(); k++) {
                jTable1.setValueAt(null, i, k);
            }
        }
        jTable1.changeSelection(0, 0, true, false);
        jTable1.clearSelection();

    }

    public void cleartext() {
        fromDateTextField.setText("");
        toDateTextField.setText("");
        totalAmountTextField.setText("");
        cleartable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        scrollLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        fromDateTextField = new javax.swing.JTextField();
        toDateTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ShowButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        totalAmountTextField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CustomerNameComboBox = new javax.swing.JComboBox();
        totalCostLabel = new javax.swing.JLabel();
        grossProfitLabel = new javax.swing.JLabel();
        totalCostTextField = new javax.swing.JTextField();
        grossProfitTextField5 = new javax.swing.JTextField();
        printButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sales View");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Sales View");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/DINESH LOGO_small.png"))); // NOI18N
        jLabel6.setText("DINESH RIBBONS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        scrollLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        scrollLabel.setForeground(new java.awt.Color(0, 204, 204));
        scrollLabel.setText("    Developed and Designed by - RAM DOCTOR                                                                                                                                                   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(scrollLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales View", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 0, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fromDateTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(fromDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, -1));

        toDateTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(toDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 150, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 470, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("From Date :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("To Date :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 70, 20));

        ShowButton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ShowButton.setText("Show");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Invoice No.", "Party Name", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 700, 360));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Total Amount :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 100, 20));

        totalAmountTextField.setEditable(false);
        totalAmountTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        totalAmountTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalAmountTextFieldMouseClicked(evt);
            }
        });
        jPanel2.add(totalAmountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 150, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/calendar_icon1(2).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 30, 20));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/calendar_icon1(2).png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 30, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Customer Name :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 20));

        CustomerNameComboBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CustomerNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL" }));
        jPanel2.add(CustomerNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 200, -1));

        totalCostLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        totalCostLabel.setText("Total Cost");
        jPanel2.add(totalCostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 100, 20));

        grossProfitLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        grossProfitLabel.setText("Gross Profit :");
        jPanel2.add(grossProfitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 100, 20));

        totalCostTextField.setEditable(false);
        totalCostTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(totalCostTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 150, -1));

        grossProfitTextField5.setEditable(false);
        grossProfitTextField5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel2.add(grossProfitTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 150, -1));

        printButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        jPanel2.add(printButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cleartext();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Calendarium cal = new Calendarium(new JFrame());
        cal.displayDate();
        fromDateTextField.setText(cal.setPickedDate());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Calendarium cal = new Calendarium(new JFrame());
        cal.displayDate();
        toDateTextField.setText(cal.setPickedDate());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void totalAmountTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalAmountTextFieldMouseClicked
       setAmountCostGrossValue();
    }//GEN-LAST:event_totalAmountTextFieldMouseClicked

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        boolean Flag = false;
        String f_date = null;
        String t_date = null;

        if (Flag == false) {
            if (fromDateTextField.getText().equals("") || fromDateTextField.getText() == null) {
                String message1 = "From date: Should not be left empty!!";
                JOptionPane.showMessageDialog(new JFrame(), message1,
                        "Error", JOptionPane.ERROR_MESSAGE);
                Flag = true;
            }


        }

        if (Flag == false) {
            if (toDateTextField.getText().equals("") || toDateTextField.getText() == null) {
                String message1 = "To Date: Should not be left empty!!";
                JOptionPane.showMessageDialog(new JFrame(), message1,
                        "Error", JOptionPane.ERROR_MESSAGE);
                Flag = true;
            }


        }

        if (Flag == false) {
            String dt = fromDateTextField.getText().toString();

            try {
                Date d1 = new SimpleDateFormat("dd-MM-yyyy").parse(dt);
                System.out.println(d1);

                DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
                f_date = df1.format(d1);
                System.out.println(f_date);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Invalid Date.\nDate Format should be (dd-MM-yyyy)");
                Flag = true;
                //Logger.getLogger(Amount_paid.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

        if (Flag == false) {
            String dt = toDateTextField.getText().toString();

            try {
                Date d1 = new SimpleDateFormat("dd-MM-yyyy").parse(dt);
                System.out.println(d1);

                DateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
                t_date = df1.format(d1);
                System.out.println(t_date);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Invalid Date.\nDate Format should be (dd-MM-yyyy)");
                Flag = true;
                //Logger.getLogger(Amount_paid.class.getName()).log(Level.SEVERE, null, ex);

            }

        }

        if (Flag == false) {

            try {
                db.dbConn();
                String CustomerName = (String) CustomerNameComboBox.getSelectedItem();
                String sql = "SELECT dc_date AS 'Date', inv_no AS 'Invoice No.', bill_to AS 'Party Name', total_amt AS 'Total Amount', total_costing AS 'Total Costing' FROM sales_details WHERE dc_date BETWEEN '" + f_date + "' AND '" + t_date + "' ";
                if (!CustomerName.equals("ALL")) {
                    sql = sql + "AND bill_to = '" + CustomerName + "'";
                }
                System.out.println(sql);
                ResultSet rs = db.statement.executeQuery(sql);


                jTable1.setModel(DbUtils.resultSetToTableModel(rs));





                totalAmountTextFieldMouseClicked(null);;
                db.dbClose();
            } catch (SQLException sqle) {
                sqle.printStackTrace();
            }
        }
    }//GEN-LAST:event_ShowButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MainScreen ss = new MainScreen();

        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        PrintPartywiseSalesDetails printPartywiseSalesDetails = new PrintPartywiseSalesDetails(CustomerNameComboBox.getSelectedItem().toString(), fromDateTextField.getText(), toDateTextField.getText());
        this.setVisible(false);
        printPartywiseSalesDetails.setVisible(true);

    }//GEN-LAST:event_printButtonActionPerformed
    private void populateCustomerNameComboBox() {
        DatabaseConnection conn = new DatabaseConnection();
        Iterator<String> iterator = conn.getCustomerNameFromSaleDetails().iterator();
        while (iterator.hasNext()) {
            CustomerNameComboBox.addItem(iterator.next());
        }
    }

    private void setAmountCostGrossValue() {
        BigDecimal total_amt = new BigDecimal(0);
        BigDecimal total_cost = new BigDecimal(0);
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            if (jTable1.getValueAt(i, 0) != null || !jTable1.getValueAt(i, 0).equals("")) {
                BigDecimal amt = BigDecimal.valueOf(Double.parseDouble(jTable1.getValueAt(i, 3).toString()));
                total_amt = total_amt.add(amt);
                
                BigDecimal cost = BigDecimal.valueOf(Double.parseDouble(jTable1.getValueAt(i, 4).toString()));
                total_cost = total_cost.add(cost);
            }
        }
        totalAmountTextField.setText(String.valueOf(total_amt));
        totalCostTextField.setText(String.valueOf(total_cost));
        grossProfitTextField5.setText(String.valueOf(total_amt.subtract(total_cost)));
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Show_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Show_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Show_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Show_sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Show_sales().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CustomerNameComboBox;
    private javax.swing.JButton ShowButton;
    private javax.swing.JTextField fromDateTextField;
    private javax.swing.JLabel grossProfitLabel;
    private javax.swing.JTextField grossProfitTextField5;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel scrollLabel;
    private javax.swing.JTextField toDateTextField;
    private javax.swing.JTextField totalAmountTextField;
    private javax.swing.JLabel totalCostLabel;
    private javax.swing.JTextField totalCostTextField;
    // End of variables declaration//GEN-END:variables
}
