/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RankaMain.java
 *
 * Created on Sep 12, 2012, 4:52:28 PM
 */
package com.dr.login;

import com.dr.amount.Add_Amount_paid;
import com.dr.amount.Add_Amount_received;
import com.dr.amount.Show_amt_paid;
import com.dr.amount.Show_amt_received;
import com.dr.challan.PrintChallan;
import com.dr.connection.DatabaseConnection;
import com.dr.cutomerDetails.Add_Customer_entry;
import com.dr.items.Add_Items;
import com.dr.purchase.Add_Purchase;
import com.dr.sales.Add_Sales;
import com.dr.password.ChangePass;
import com.dr.purchase.Delete_purchase;
import com.dr.sales.Delete_sales;
import com.dr.purchase.Show_purchase;
import com.dr.sales.Show_sales;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.Timer;


/**
 *
 * @author Eesha
 */
public class MainScreen extends javax.swing.JFrame implements ActionListener{

    private javax.swing.JMenuItem jMenuItem100;
    private String address;
    private String phone;
    private String fax;
    private String email;
    private String compName;
    
    private String unitName;
    private byte[] imageData;
    ResultSet rs=null;
    ResultSet rs2=null;
    ImageIcon format;
    
    private static MainScreen instance=null;
    /** Creates new form RankaMain */
    public MainScreen() {
        initComponents();
        
        
        
        Timer timer = new Timer(DELAY_TIME,this);
        timer.start();
        setLocationRelativeTo(null);
        
      
       //jTextField1.setText(db.getUnitAddr(unitName));
        //setAlwaysOnTop(true);
        
        
    }

    public static MainScreen getInstance()
    {

    if(instance == null)
    {
    instance = new MainScreen();
    }

    //returns the same instance everytime MySingleFrame.getInstance() is called
    return instance; 

    }
    

    //Ram Doctor
    public void setPasswordMenuInvisible()
    {
        DatabaseConnection db = new DatabaseConnection();
        String text = db.getUser();
        welcomeField.setText("Welcome " +text+"!");
        changePassword.setVisible(false);
        
        Items.setVisible(false);
        
        
        
        setVisible(true);
    }
    
    //Ram Doctor
    public void setPasswordMenuVisible()
    {
        DatabaseConnection db = new DatabaseConnection();
        String text = db.getUser();
        welcomeField.setText("Welcome " +text+"!");
        changePassword.setVisible(true);
        
        Items.setVisible(true);
       
        
        setVisible(true);
    }
    

    
    
    
    @Override
    public void actionPerformed(ActionEvent e)  {
      String oldText = scrollLabel1.getText();
      String newText = oldText.substring(1) + oldText.substring(0, 1);
      scrollLabel1.setText( newText );
      String oldT = scrollLabel2.getText();
      String newT = oldT.substring(1) + oldT.substring(0, 1);
      scrollLabel2.setText( newT );
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        scrollLabel1 = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        logout = new javax.swing.JButton();
        Delete_sales = new javax.swing.JPanel();
        SalesInvoiceButton = new javax.swing.JButton();
        PurchaseOrderButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CustomerButton = new javax.swing.JButton();
        ItemsButton = new javax.swing.JButton();
        CompanyButton = new javax.swing.JButton();
        UnitButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        welcomeField = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        scrollLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MasterMenu = new javax.swing.JMenu();
        Customer = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Items = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Company = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Unit = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        TransactionMenu = new javax.swing.JMenu();
        SalesInvoice = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        PurchaseOrder = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        ReportsMenu = new javax.swing.JMenu();
        SalesReport = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        ExciseReport = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        DeliveryReports = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        InternalDilveryReports = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        printMenu = new javax.swing.JMenu();
        printChallanMenuItem = new javax.swing.JMenuItem();
        changePassword = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("DInesh Ribbons");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jPanel3.setBackground(new java.awt.Color(0, 204, 153));

        scrollLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 18)); // NOI18N
        scrollLabel1.setForeground(new java.awt.Color(0, 102, 102));
        scrollLabel1.setText("                Dinesh Ribbons, A 25 Years Experience in market                   manufacturing :  all kind of laces and Borders.");
        scrollLabel1.setIconTextGap(12);

        headingLabel.setBackground(new java.awt.Color(0, 204, 153));
        headingLabel.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        headingLabel.setForeground(new java.awt.Color(0, 102, 102));
        headingLabel.setText("         Sales Invoicing System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scrollLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(scrollLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        logout.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 204, 204));
        logout.setText("LogOut");
        logout.setToolTipText("Close");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });

        Delete_sales.setBackground(new java.awt.Color(0, 153, 153));

        SalesInvoiceButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SalesInvoiceButton.setForeground(new java.awt.Color(0, 153, 153));
        SalesInvoiceButton.setText("Sales Invoice");
        SalesInvoiceButton.setToolTipText("Sales Invoice");
        SalesInvoiceButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalesInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesInvoiceButtonActionPerformed(evt);
            }
        });

        PurchaseOrderButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        PurchaseOrderButton.setForeground(new java.awt.Color(0, 153, 153));
        PurchaseOrderButton.setText("Purchase Order");
        PurchaseOrderButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PurchaseOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseOrderButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 153));
        jLabel12.setText("  Transaction");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("      Master");

        CustomerButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CustomerButton.setForeground(new java.awt.Color(0, 153, 153));
        CustomerButton.setText("Buyer & Supplier");
        CustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerButtonActionPerformed(evt);
            }
        });

        ItemsButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ItemsButton.setForeground(new java.awt.Color(0, 153, 153));
        ItemsButton.setText("Items");
        ItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsButtonActionPerformed(evt);
            }
        });

        CompanyButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        CompanyButton.setForeground(new java.awt.Color(0, 153, 153));
        CompanyButton.setText("Amount Paid");
        CompanyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyButtonActionPerformed(evt);
            }
        });

        UnitButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        UnitButton.setForeground(new java.awt.Color(0, 153, 153));
        UnitButton.setText("Amount Received");
        UnitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitButtonActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 153, 153));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setText("Delete");

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 153));
        jButton1.setText("Delete Sales");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 153, 153));
        jButton2.setText("Delete Purchase");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Delete_salesLayout = new javax.swing.GroupLayout(Delete_sales);
        Delete_sales.setLayout(Delete_salesLayout);
        Delete_salesLayout.setHorizontalGroup(
            Delete_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_salesLayout.createSequentialGroup()
                .addGroup(Delete_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Delete_salesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Delete_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalesInvoiceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PurchaseOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompanyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UnitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Delete_salesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(Delete_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(Delete_salesLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Delete_salesLayout.setVerticalGroup(
            Delete_salesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_salesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SalesInvoiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PurchaseOrderButton)
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CustomerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemsButton)
                .addGap(4, 4, 4)
                .addComponent(CompanyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UnitButton)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        welcomeField.setEditable(false);
        welcomeField.setBackground(new java.awt.Color(0, 204, 153));
        welcomeField.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        welcomeField.setForeground(new java.awt.Color(255, 204, 0));
        welcomeField.setBorder(null);

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 153));
        jDesktopPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jDesktopPane1.setForeground(new java.awt.Color(0, 102, 102));

        image.setBackground(new java.awt.Color(0, 204, 204));
        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dr/images/DINESH LOGO.jpg"))); // NOI18N
        jDesktopPane1.add(image);
        image.setBounds(10, 0, 270, 270);

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        scrollLabel2.setBackground(new java.awt.Color(255, 255, 255));
        scrollLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        scrollLabel2.setForeground(new java.awt.Color(0, 204, 204));
        scrollLabel2.setText("    Developed and Designed by - Ram Doctor                                                                                                                         ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(scrollLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Dinesh Ribbons");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Delete_sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(welcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(404, 404, 404)
                                .addComponent(logout))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(241, 241, 241))))))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Delete_sales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(165, 30));

        MasterMenu.setBackground(new java.awt.Color(236, 233, 216));
        MasterMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MasterMenu.setForeground(new java.awt.Color(0, 204, 204));
        MasterMenu.setText("   Master");
        MasterMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Customer.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Customer.setForeground(new java.awt.Color(0, 204, 204));
        Customer.setText("Buyer & Supplier");
        Customer.setPreferredSize(new java.awt.Dimension(200, 18));
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        MasterMenu.add(Customer);

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        MasterMenu.add(jSeparator3);

        Items.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Items.setForeground(new java.awt.Color(0, 204, 204));
        Items.setText("Items");
        Items.setPreferredSize(new java.awt.Dimension(160, 18));
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        MasterMenu.add(Items);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        MasterMenu.add(jSeparator1);

        Company.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Company.setForeground(new java.awt.Color(0, 204, 204));
        Company.setText("Amount Paid");
        Company.setPreferredSize(new java.awt.Dimension(160, 18));
        Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyActionPerformed(evt);
            }
        });
        MasterMenu.add(Company);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        MasterMenu.add(jSeparator2);

        Unit.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Unit.setForeground(new java.awt.Color(0, 204, 204));
        Unit.setText("Amount Received");
        Unit.setPreferredSize(new java.awt.Dimension(160, 18));
        Unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnitActionPerformed(evt);
            }
        });
        MasterMenu.add(Unit);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        MasterMenu.add(jSeparator4);

        jMenuBar1.add(MasterMenu);

        TransactionMenu.setBackground(new java.awt.Color(236, 233, 216));
        TransactionMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TransactionMenu.setForeground(new java.awt.Color(0, 204, 204));
        TransactionMenu.setText("Transaction");
        TransactionMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        SalesInvoice.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        SalesInvoice.setForeground(new java.awt.Color(0, 204, 204));
        SalesInvoice.setText("Sales Invoice");
        SalesInvoice.setPreferredSize(new java.awt.Dimension(200, 18));
        SalesInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesInvoiceActionPerformed(evt);
            }
        });
        TransactionMenu.add(SalesInvoice);

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        TransactionMenu.add(jSeparator5);

        PurchaseOrder.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        PurchaseOrder.setForeground(new java.awt.Color(0, 204, 204));
        PurchaseOrder.setText("Purchase Order");
        PurchaseOrder.setPreferredSize(new java.awt.Dimension(160, 18));
        PurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseOrderActionPerformed(evt);
            }
        });
        TransactionMenu.add(PurchaseOrder);

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        TransactionMenu.add(jSeparator6);

        jMenuBar1.add(TransactionMenu);

        ReportsMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReportsMenu.setForeground(new java.awt.Color(0, 204, 204));
        ReportsMenu.setText("  Reports");
        ReportsMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ReportsMenu.setPreferredSize(new java.awt.Dimension(75, 19));

        SalesReport.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        SalesReport.setForeground(new java.awt.Color(0, 204, 204));
        SalesReport.setText("Show Sales");
        SalesReport.setPreferredSize(new java.awt.Dimension(200, 18));
        SalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesReportActionPerformed(evt);
            }
        });
        ReportsMenu.add(SalesReport);

        jSeparator14.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        ReportsMenu.add(jSeparator14);

        ExciseReport.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        ExciseReport.setForeground(new java.awt.Color(0, 204, 204));
        ExciseReport.setText("Show Purchase");
        ExciseReport.setPreferredSize(new java.awt.Dimension(160, 18));
        ExciseReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExciseReportActionPerformed(evt);
            }
        });
        ReportsMenu.add(ExciseReport);

        jSeparator15.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator15.setForeground(new java.awt.Color(0, 0, 0));
        ReportsMenu.add(jSeparator15);

        DeliveryReports.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        DeliveryReports.setForeground(new java.awt.Color(0, 204, 204));
        DeliveryReports.setText("Show Amount Paid");
        DeliveryReports.setPreferredSize(new java.awt.Dimension(160, 18));
        DeliveryReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryReportsActionPerformed(evt);
            }
        });
        ReportsMenu.add(DeliveryReports);

        jSeparator16.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator16.setForeground(new java.awt.Color(0, 0, 0));
        ReportsMenu.add(jSeparator16);

        InternalDilveryReports.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        InternalDilveryReports.setForeground(new java.awt.Color(0, 204, 204));
        InternalDilveryReports.setText("Show Amount Received");
        InternalDilveryReports.setPreferredSize(new java.awt.Dimension(160, 18));
        InternalDilveryReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternalDilveryReportsActionPerformed(evt);
            }
        });
        ReportsMenu.add(InternalDilveryReports);

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        ReportsMenu.add(jSeparator8);

        jMenuBar1.add(ReportsMenu);

        printMenu.setForeground(new java.awt.Color(0, 204, 204));
        printMenu.setText("Print    ");
        printMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        printChallanMenuItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        printChallanMenuItem.setForeground(new java.awt.Color(0, 204, 204));
        printChallanMenuItem.setText("Print Challan");
        printChallanMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printChallanMenuItemActionPerformed(evt);
            }
        });
        printMenu.add(printChallanMenuItem);

        jMenuBar1.add(printMenu);

        changePassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changePassword.setForeground(new java.awt.Color(0, 204, 204));
        changePassword.setText("Change Password");
        changePassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jMenuItem7.setForeground(new java.awt.Color(0, 204, 204));
        jMenuItem7.setText("Change User Password");
        jMenuItem7.setPreferredSize(new java.awt.Dimension(200, 18));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        changePassword.add(jMenuItem7);

        jSeparator9.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        changePassword.add(jSeparator9);

        jMenuBar1.add(changePassword);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public MainScreen(JMenuItem jMenuItem9) {
       // this.jMenuItem9 = jMenuItem9;
    }

    private void UnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitActionPerformed
        UnitButtonActionPerformed(evt);
        //setVisible(false);
    }//GEN-LAST:event_UnitActionPerformed

    private void SalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesReportActionPerformed
       // PrintSales ps = new PrintSales();
        Show_sales ss= new Show_sales();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_SalesReportActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ChangePass cp = new ChangePass();
        setVisible(false);
        cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_logOutMouseClicked

    private void ItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsButtonActionPerformed
        // TODO add your handling code here:
        Add_Items ss=new Add_Items();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_ItemsButtonActionPerformed

    //Ram Doctor
    private void SalesInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesInvoiceButtonActionPerformed
//        // TODO add your handling code here:
        Add_Sales ss=new Add_Sales();
        
        setVisible(false);
        ss.setVisible(true);
        
    }//GEN-LAST:event_SalesInvoiceButtonActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        // TODO add your handling code here:
        CustomerButtonActionPerformed(evt);
    }//GEN-LAST:event_CustomerActionPerformed

    private void SalesInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesInvoiceActionPerformed
        // TODO add your handling code here:
        SalesInvoiceButtonActionPerformed(evt);
    }//GEN-LAST:event_SalesInvoiceActionPerformed

    private void CustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerButtonActionPerformed
        // TODO add your handling code here:
        Add_Customer_entry ss=new Add_Customer_entry();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_CustomerButtonActionPerformed

    private void CompanyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyButtonActionPerformed
        // TODO add your handling code here:
        Add_Amount_paid ss= new Add_Amount_paid();
        
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_CompanyButtonActionPerformed

    private void UnitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnitButtonActionPerformed
        // TODO add your handling code here:
        Add_Amount_received ss=new Add_Amount_received();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_UnitButtonActionPerformed

    private void PurchaseOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseOrderButtonActionPerformed
        // TODO add your handling code here:
        Add_Purchase ss=new Add_Purchase();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_PurchaseOrderButtonActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        // TODO add your handling code here:
        ItemsButtonActionPerformed(evt);
    }//GEN-LAST:event_ItemsActionPerformed

    private void CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyActionPerformed
        // TODO add your handling code here:
        CompanyButtonActionPerformed(evt);
    }//GEN-LAST:event_CompanyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        String message = "Please Logged out first..";
        JOptionPane.showMessageDialog(new JFrame(), message,
            "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_formWindowClosing

    private void PurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseOrderActionPerformed
        // TODO add your handling code here:
        PurchaseOrderButtonActionPerformed(evt);
    }//GEN-LAST:event_PurchaseOrderActionPerformed

    private void InternalDilveryReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternalDilveryReportsActionPerformed
        // TODO add your handling code here:
        Show_amt_received ss=new Show_amt_received();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_InternalDilveryReportsActionPerformed

    private void ExciseReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExciseReportActionPerformed
        // TODO add your handling code here:
        Show_purchase ss=new Show_purchase();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_ExciseReportActionPerformed

    private void DeliveryReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryReportsActionPerformed
        // TODO add your handling code here:
        Show_amt_paid ss=new Show_amt_paid();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_DeliveryReportsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Delete_sales ss=new Delete_sales();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Delete_purchase ss =new Delete_purchase();
        
        setVisible(false);
        ss.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void printChallanMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printChallanMenuItemActionPerformed
       PrintChallan printChallan = new PrintChallan();
       setVisible(false);
       printChallan.setVisible(true);
    }//GEN-LAST:event_printChallanMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }
    
    //user variables
    private static final int DELAY_TIME = 165;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Company;
    private javax.swing.JButton CompanyButton;
    private javax.swing.JMenuItem Customer;
    private javax.swing.JButton CustomerButton;
    private javax.swing.JPanel Delete_sales;
    private javax.swing.JMenuItem DeliveryReports;
    private javax.swing.JMenuItem ExciseReport;
    private javax.swing.JMenuItem InternalDilveryReports;
    private javax.swing.JMenuItem Items;
    private javax.swing.JButton ItemsButton;
    private javax.swing.JMenu MasterMenu;
    private javax.swing.JMenuItem PurchaseOrder;
    private javax.swing.JButton PurchaseOrderButton;
    private javax.swing.JMenu ReportsMenu;
    private javax.swing.JMenuItem SalesInvoice;
    private javax.swing.JButton SalesInvoiceButton;
    private javax.swing.JMenuItem SalesReport;
    private javax.swing.JMenu TransactionMenu;
    private javax.swing.JMenuItem Unit;
    private javax.swing.JButton UnitButton;
    private javax.swing.JMenu changePassword;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JButton logout;
    private javax.swing.JMenuItem printChallanMenuItem;
    private javax.swing.JMenu printMenu;
    private javax.swing.JLabel scrollLabel1;
    private javax.swing.JLabel scrollLabel2;
    private javax.swing.JTextField welcomeField;
    // End of variables declaration//GEN-END:variables
}
